# Generated by Django 4.0.5 on 2022-09-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bauthor', models.CharField(max_length=100)),
                ('bsubject', models.CharField(max_length=100)),
                ('bprice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
