# Generated by Django 3.2.7 on 2022-09-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
    ]
